let nom = "Williams";
let prenom = "Mikey";
let age = 21;
let estMajeur = true;
let tableau =[1,2,3,4,5];


console.log(nom);
console.log(prenom);
console.log(age);
console.log(estMajeur);
console.log(tableau);
console.log("Je suis " + nom + " " + prenom);




//Math is Mathing
console.log(2+2)
console.log(2-2)
console.log(2+2-3)
console.log(2-3)
console.log(2*2)

let x = 3; // x contient la valeur 3
let y = 4; // y contient la valeur 4
console.log(2*2+x)

console.log(2**10)
console.log(4**2)
let name = 'Stanley'
console.log(name)